#!/bin/sh

# Set these paths appropriately

BIN=/Users/noodle/workspace/python/PCML/project2/tree-tagger/bin
CMD=/Users/noodle/workspace/python/PCML/project2/tree-tagger/cmd
LIB=/Users/noodle/workspace/python/PCML/project2/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/middle-high-german-abbreviations-utf8
PARFILE=${LIB}/middle-high-german-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
