#!/bin/sh

# Set these paths appropriately

BIN=/Users/noodle/workspace/python/PCML/project2/tree-tagger/bin
CMD=/Users/noodle/workspace/python/PCML/project2/tree-tagger/cmd
LIB=/Users/noodle/workspace/python/PCML/project2/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/tokenize.pl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/latin-abbreviations
PARFILE=${LIB}/latin.par
MWLFILE=${LIB}/latin-mwls

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE

