#!/bin/sh

# Set these paths appropriately

BIN=/Users/noodle/workspace/python/PCML/project2/tree-tagger/bin
CMD=/Users/noodle/workspace/python/PCML/project2/tree-tagger/cmd
LIB=/Users/noodle/workspace/python/PCML/project2/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
